spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_user_name
    password: your_user_password
  jpa:
    properties:
      hibernate.hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop



server:
  port: 8443
  ssl:
    enabled: true

    key-store: classpath:server-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12

    trust-store: classpath:server-truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12

    client-auth: want # <- mTLS ??

jwt:
  secret: MyVeryLongAndSecureSecretKeyForHS256Algorithm
  expiration-time: 3600000

logging:
  level:
    org.hibernate.sql: debug
    org.springframework.security: DEBUG # Spring Security? ?? ??? ?????.
    com.example.demo.service: DEBUG     # ?? ?? VehicleDetailsService? ??? ?????.